[project]
name = "nds_dedx_database"
dynamic = ["version"]
description = "Python package for the Experimental Stopping Database, a collection of experimental stopping power data for various materials and particles."
readme = "README.md"
authors = [{name = "Arto Javanainen", email = "arto.javanainen@jyu.fi"}]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "periodictable>=2.0.2",
    "plotly>=6.1.2",
    "polars>=1.40.1",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.2.3.250527",]
test = [
    "pytest>=8.4.0",
    "pytest-cov>=7.1.0",
]
notebooks = [
    "jupyterlab>=3.0.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "jupyter>=1.1.1",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
dirty = true
pattern = "default-unprefixed"
# style = "semver"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nds_dedx_database"]
include = [
    "nds_dedx_database/package_data/latest/*.csv",
]
